/**
 * WaveDirectorBrain — agent interface for the v4 adversarial side.
 *
 * Where BotBrain decides what towers to PLACE, WaveDirectorBrain
 * decides what creeps to SPAWN. It replaces the static
 * `getWavesForMode()` generator: same shape of output (a list of
 * `WaveDefinition`) but generated by an agent that can adapt to the
 * defender's strategy.
 *
 * **Hard invariant**: a WaveDirector picks creep compositions only.
 * It cannot grant creeps tower-damaging abilities, change the win
 * condition, or skip waves. Outcome model is identical to current
 * TD: more creeps reach exit → more lives lost → defender loses
 * faster. Towers are untouchable.
 *
 * **NOT to be confused with** the in-game "send" mechanic, which is
 * a versus-mode player action that costs gold and queues an extra
 * burst into the opponent's lane. Sends are separate from
 * WaveDirectorBrain — they remain a player tool, not the adversary's.
 *
 * v4.1 ships this interface plus `UniformWaveDirector` (a no-op wrapper
 * around `getWavesForMode`). v4.2+ adds smarter directors
 * (`CounterPickWaveDirector`, `AdversarialSearchWaveDirector`) that
 * observe the defender's tower placements and pick exploitative mixes.
 */
import { WaveDefinition, MatchMode } from '../../data/WaveDefinitions';
import { PathPoint } from '../Pathfinding';

/** Context the director sees at materialization time. v4.1 needs only
 *  mode + count; v4.2+ adds observed-tower / observed-path inputs for
 *  reactive directors. */
export interface WaveDirectorMaterializeContext {
  matchMode: MatchMode;
  /** Total waves the match expects (undefined → mode default). */
  waveCount?: number;
  /** Faction the defender is playing — director can use this to bias
   *  away from creep types that match the defender's strengths
   *  (e.g. spawn fast creeps when faction has no slow towers). v4.1's
   *  uniform director ignores it. */
  defenderFaction: string;
}

/** v4.2: per-wave context the director sees when generating the next
 *  wave on demand. Includes the live observation of the defender's
 *  state so reactive directors can respond to actual placements
 *  rather than just match-start config. */
export interface WaveObservation {
  /** 1-indexed wave number being generated. */
  waveIndex: number;
  /** Defender's lives remaining. */
  livesRemaining: number;
  /** Faction the defender is playing. */
  defenderFaction: string;
  /** Towers the defender has placed up to this point. Reactive
   *  directors inspect this to pick creep mixes that exploit gaps. */
  observedTowers: { col: number; row: number; towerId: string; level: number }[];
  /** Current creep path (after towers redirected it). */
  observedPath: PathPoint[] | null;
}

export interface WaveDirectorBrain {
  /** Stable id used in MatchConfig and registries. */
  readonly name: string;

  /** v4.2: called once at match start before any waves run. Lets the
   *  director precompute state (e.g. UniformWaveDirector materializes
   *  the full static wave list once and serves from cache). */
  init(ctx: WaveDirectorMaterializeContext): void;

  /** v4.2: lazy per-wave generation. Called between waves with the
   *  current observation; returns the next wave's composition. The
   *  controller appends the returned WaveDefinition to its working
   *  waves[] array. */
  nextWave(obs: WaveObservation): WaveDefinition;

  /** v4.1 legacy: build the full wave list upfront. Optional now —
   *  callers can use init+nextWave instead. UniformWaveDirector still
   *  implements this so v4.1 callers (and the test suite) keep working. */
  materializeWaves?(ctx: WaveDirectorMaterializeContext): WaveDefinition[];
}

const registry = new Map<string, () => WaveDirectorBrain>();

/** Register a director factory. Called as a side-effect import in
 *  `HeadlessMatch.ts` (or wherever directors are first needed) so
 *  the id resolves at runtime. */
export function registerWaveDirector(id: string, factory: () => WaveDirectorBrain): void {
  registry.set(id, factory);
}

/** Look up a registered director by id. Returns null when absent —
 *  callers fall back to the legacy static-wave path in that case. */
export function getWaveDirector(id: string): WaveDirectorBrain | null {
  const factory = registry.get(id);
  return factory ? factory() : null;
}

/** Diagnostic: list all registered director ids. */
export function listWaveDirectors(): string[] {
  return [...registry.keys()];
}
