/**
 * WaveDirectorBrain — agent interface for the v4 adversarial side.
 *
 * Where BotBrain decides what towers to PLACE, WaveDirectorBrain
 * decides what creeps to SPAWN. It replaces the static
 * `getWavesForMode()` generator: same shape of output (a list of
 * `WaveDefinition`) but generated by an agent that can adapt to the
 * defender's strategy.
 *
 * **Hard invariant**: a WaveDirector picks creep compositions only.
 * It cannot grant creeps tower-damaging abilities, change the win
 * condition, or skip waves. Outcome model is identical to current
 * TD: more creeps reach exit → more lives lost → defender loses
 * faster. Towers are untouchable.
 *
 * **NOT to be confused with** the in-game "send" mechanic, which is
 * a versus-mode player action that costs gold and queues an extra
 * burst into the opponent's lane. Sends are separate from
 * WaveDirectorBrain — they remain a player tool, not the adversary's.
 *
 * v4.1 ships this interface plus `UniformWaveDirector` (a no-op wrapper
 * around `getWavesForMode`). v4.2+ adds smarter directors
 * (`CounterPickWaveDirector`, `AdversarialSearchWaveDirector`) that
 * observe the defender's tower placements and pick exploitative mixes.
 */
import { WaveDefinition, MatchMode } from '../../data/WaveDefinitions';

/** Context the director sees at materialization time. v4.1 needs only
 *  mode + count; v4.2+ adds observed-tower / observed-path inputs for
 *  reactive directors. */
export interface WaveDirectorMaterializeContext {
  matchMode: MatchMode;
  /** Total waves the match expects (undefined → mode default). */
  waveCount?: number;
  /** Faction the defender is playing — director can use this to bias
   *  away from creep types that match the defender's strengths
   *  (e.g. spawn fast creeps when faction has no slow towers). v4.1's
   *  uniform director ignores it. */
  defenderFaction: string;
}

export interface WaveDirectorBrain {
  /** Stable id used in MatchConfig and registries. */
  readonly name: string;
  /** Build the full wave list for the match. Called once at match
   *  start. Future directors that need per-wave reaction will lazily
   *  generate via a `nextWave(ctx)` callback (v4.2+); for now this
   *  upfront-materialize signature matches the static-generator API. */
  materializeWaves(ctx: WaveDirectorMaterializeContext): WaveDefinition[];
}

const registry = new Map<string, () => WaveDirectorBrain>();

/** Register a director factory. Called as a side-effect import in
 *  `HeadlessMatch.ts` (or wherever directors are first needed) so
 *  the id resolves at runtime. */
export function registerWaveDirector(id: string, factory: () => WaveDirectorBrain): void {
  registry.set(id, factory);
}

/** Look up a registered director by id. Returns null when absent —
 *  callers fall back to the legacy static-wave path in that case. */
export function getWaveDirector(id: string): WaveDirectorBrain | null {
  const factory = registry.get(id);
  return factory ? factory() : null;
}

/** Diagnostic: list all registered director ids. */
export function listWaveDirectors(): string[] {
  return [...registry.keys()];
}
