import { UIBridge } from '../UIBridge';
import { ShardBadge } from '../components/ShardBadge';
import { Header } from '../components/Header';

type Entry = {
  date: string;
  title: string;
  changes: string[];
};

const ENTRIES: Entry[] = [
  {
    date: '2026-05-01',
    title: 'High-res art v2 + parallax delivery + LoadingScreen splash + game-stuck fixes',
    changes: [
      'Adopted high_res_art_v2/: 4× larger emblems (5016×5016 sheet) and splashes (2164×816 each, individual files), plus net-new image_c.png parallax sheet (6144×4096) with all 33 layer cells (11 factions × far/mid/fore)',
      'Updated scripts/slice_high_res_art.py — auto-detects emblem cell columns, hand-tuned y-bands per row (top vs bottom rows have different label positions; image-then-label on top, label-before-image on bottom), and slices the parallax sheet into 1008×~180 (top) and 1212×~120 (bottom) per-layer PNGs',
      'LoadingScreen now renders the player\'s faction splash key art as a 35%-opacity background with a radial vignette over it for text readability. Hides cleanly on load failure / meta factions (chaos / random)',
      'MissionRunner faction default → arcane: campaign missions without an explicit faction override fell back to the generic Arrow/Cannon/Sniper/Frost-Trap pool. Long-term fix is a pre-mission faction picker; this is the shipping fix',
      'WaveController auto-recovery after 30s stuck: if a wave has no active spawns/sends but creeps remain (typically a mis-pathed creep after a tower placement), the controller calls onStuckForceClear which marks every alive creep as `reached`. Wave clears, player loses lives proportional to leaks, match continues. Without this a single mis-pathed creep could hang the entire match',
      '438/438 vitest pass, tsc clean',
    ],
  },
  {
    date: '2026-04-30',
    title: 'Art pass extracted + Plans 11/13 v1 (Base Defense + Heist) + art PRD',
    changes: [
      'Sliced 55 PNGs from a single composite art-pass file (resources/composite_art_theme.png) into per-faction emblems / welcome splashes / parallax-layer triplets at public/assets/{faction}/. Sliced via scripts/slice_art_pass.py — column boundaries auto-detected for A1 emblems, hand-tuned for A2 splashes (designer used different alignment), even-spaced for A3 parallax (LAYER label gutter)',
      'FactionEmblem switched to PNG-first: renders /assets/{faction}/{faction}_emblem.png with a CSS grayscale filter for the locked state, falls back to the procedural SVG glyph if the image fails to load (or for chaos / random which don\'t ship art)',
      'FactionUnlockSplash overlays the per-faction splash key art behind the existing emblem + text, with a darkening radial vignette over it for legibility. Self-hides the <img> on load failure',
      'FactionTreeScreen layers in the focused faction\'s 3-layer parallax (far / mid / fore) when a node is selected. Pan rates per the PRD A3 spec — far at 240s/cycle, mid at 120s, fore at 60s. The starfield default still renders when no node is focused',
      'Plan 11 — Base Defense archetype shipped v1. New base_arena map (4 perimeter spawners → central exit, 3x3 noBuild ring around the base, corner pillars stop full-perimeter walling). Reuses Standard mode mechanics; "base" is the central exit cell + standard lives counter. v2 will add a bespoke Base entity with HP bar / damage states',
      'Plan 13 — Heist archetype shipped v1. New heist_vault map (vault-themed structure on east edge spawning west). Reverse direction. Gold-on-ground mechanic deferred to v2 (needs new GoldDrop entity + per-creep carriedGold field)',
      'Plan 12 — Attacker stays stubbed; the role-reversal needs net-new engine surface (creep-send picker UI, AI defender driver, win-by-leak condition). Tracked separately',
      'New art_prd.md in notes/ — production PRD covering 50+ assets across 6 categories (faction visual identity, campaign content, tutorial / onboarding, profile / progression, generic UI, future Hero Defense). Per asset: code, purpose, dimensions, format, composition spec, animation requirements, acceptance criteria, priority',
      '+8 unit tests on archetype unstubs + new map shapes; FactionEmblem tests rewritten for PNG-first behavior with SVG fallback. 438/438 vitest pass',
    ],
  },
  {
    date: '2026-04-30',
    title: 'Bespoke Arcane maps + procedural faction emblems + tree polish + unlock splash',
    changes: [
      'Three new Arcane-tileset maps: arcane_outskirts (mission 1 opener — single-path with crystal cluster), arcane_pass (mission 6 speedrun — long winding S through crystal walls), arcane_throne (mission 10 final showdown — three-entry fortified arena with central nexus + dais)',
      'All three use the existing arcane_crystal terrain theme so blocked cells render as crystal formations. Arcane campaign updated — missions 1, 6, 10 now play on bespoke maps instead of plains/serpentine/siege',
      'New FactionEmblem component — procedural SVG circular crest with per-faction geometric glyph (Arcane: 4-pointed star, Mech: gear, Nature: 3-petal flower, Void: spiral, Military: chevrons, Aliens: hexagon hive, Cypherpunk: bracket-circuit, Infernal: flame, Celestial: sun rays, Psionic: brain-wave arcs, Harmonic: 3-circle network). Reads colors from the existing FACTIONS data; locked variant uses a muted #444/#666 palette',
      'Faction tree visual polish: animated CSS starfield drifting at 60s/loop, per-tier "↓" dividers, 2.4s pulsing halo on every unlockable node so the next-step is visually obvious',
      'Detail panel now shows the big emblem next to the faction name + tier line',
      'New FactionUnlockSplash component — full-screen take-over after a Shards purchase succeeds. Listens for the new td-faction-unlocked window event (dispatched by attemptFactionUnlock). Big animated emblem with color-tinted drop-shadow glow, faction identity copy, "Begin Campaign" CTA when content is shipped or "Continue" otherwise',
      'No bespoke art assets — every visual is procedural CSS / SVG. When real per-faction illustrations land later they drop into the same shells without engine changes',
      '+12 unit tests on the new maps (registration, theme, entries/exits, campaign references) + emblem component (renders for all 12 factions, respects size prop, locked silhouette)',
    ],
  },
  {
    date: '2026-04-30',
    title: 'Mission restrictions enforced + custom counters wired (Plan 14 v1.1)',
    changes: [
      'noSends + noFrontier mission restrictions now enforced at runtime — both the keyboard send paths and the DOM send / frontier purchase callbacks short-circuit with a "Restricted by mission" event-log message instead of silently failing',
      'GameModeContext gained `missionRestrictions` field — modes read it to gate purchases. StandardMode + BaseFrontierMode wire the noSends / noFrontier checks',
      'Custom counters added at GameScene: `_missionSendsBought` (incremented on `sendPurchased` event) + `_missionHeroHpMinFraction` (sampled per-frame from arenaManager.hero). Both fed into MissionResult.custom at game-end so star predicates can read them',
      'Two of the four placeholder Arcane predicates now real: mission 3 "Hero never falls below 50% HP" reads heroHpMin; mission 4 "Win without buying any sends" reads sendsBought. Star-3 reachability restored on those two',
      'Two predicates still placeholder — mission 5 "Kill every warlord before halfway" needs per-creep distance tracking; mission 9 "Ally never below 5 lives" needs co-op state inspection. Deferred until those surfaces get the right hooks',
      '+5 unit tests on the new counter-driven predicates (positive / negative / loss-with-full-HP cases)',
    ],
  },
  {
    date: '2026-04-30',
    title: 'Faction Tree — unlock-via-Shards-and-campaign progression UI (Plan 5)',
    changes: [
      'Tree shape locked: Arcane (free root, L1) → Mech / Nature / Void at L3 (1000 Shards) → 6 specialists at L6 (1500 Shards) → Harmonic capstone at L18 (2000 Shards, requires any 4 unlocked)',
      'Specialist groupings (per user lock): Mech parents Military + Celestial. Nature parents Aliens + Infernal. Void parents Psionic + Cypherpunk',
      'Two-step unlock model — pay Shards → unlocks the campaign for that faction → beat the campaign → faction becomes playable in every other mode. Arcane is free root and always playable. Other factions all require this gauntlet',
      'New `FactionTreeScreen` (Preact) — tier-bucketed tree layout, per-node state machine (locked-by-level / locked-by-parents / locked-capstone-N / unlockable / campaign-pending / campaign-in-progress / playable), detail panel with faction brief + tower kit preview + state-appropriate CTA',
      'New `attemptFactionUnlock` flow — checks Shards balance, parent gates, level gate, capstone N-of-any. Emits `faction_unlock_attempted/_unlocked/_failed` analytics. No rerolls / no refunds (locked by user)',
      'PlayerProfile migration extended — any faction the legacy player already had unlocked gets pre-marked playable via `legacy_faction_playable.<id>` flags. Veterans keep their full roster; new players have only Arcane',
      '`FactionSelectScreen` switched from old PlayerInventory.ownsFaction (legacy FREE_FACTIONS bake-in) to Plan-5-aware `isFactionPlayable`. Locked factions now silhouette-tap to the Faction Tree screen rather than offering a one-shot Shards spend',
      'Menu has a Factions tile at L3+ that opens the tree. Replaces the temporary single-Campaigns tile from Plan 14',
      'New "faction-tree" ScreenId in UIBridge',
      'Arcane campaign serves as the demo — beating it earns Cores + cosmetics rather than unlocking a faction. Every other tier-1+ faction shows "Campaign Coming Soon" until its content ships',
      '+25 unit tests on tree shape (locks the agreed groupings), faction node state machine, purchase flow with insufficient-shards / already-purchased / level-gate / parent-gate / capstone N-of-any scenarios',
    ],
  },
  {
    date: '2026-04-30',
    title: 'Arcane campaign — first complete 10-mission campaign (Plan 14 v1)',
    changes: [
      'Arcane Reckoning campaign: 10 missions vs Arcane creeps, mixing 6 archetypes — Restriction (mission 1: first 4 towers only, mission 4: no walls), Standard (mission 2: serpent pass, mission 8: 25-wave siege), Hero Duel (mission 3: Arcanist vs Archmage), Boss Rush (mission 5), Speedrun (mission 6), Frugal (mission 7), Bot Ally co-op (mission 9), Final Showdown (mission 10: 30 waves on siege map)',
      'Each mission has terse-mechanical story copy (~50 words) — narrative tone is medieval-fantasy report style, no in-character flourish, no canon hardlock',
      'Star objectives per mission: 1 star = win, 2 stars = win + bonus condition (no leaks / fast clear / lives remaining etc.), 3 stars = stricter condition (perfect run / under N minutes etc.)',
      'Several star predicates are placeholders (`() => false`) where the underlying counter doesn\'t yet exist — hero HP-floor tracking, send count, per-creep "killed before halfway" markers. Players still earn 2 stars via the simpler condition; 3 stars on those missions waits for the counter pass',
      'Arcane is the free root faction so beating this campaign rewards Cores + cosmetics rather than unlocking a new faction. It\'s the proof-of-concept demo before the Mechanical campaign (Chunk C) lands with real unlock-to-play stakes',
      'New Campaigns tile on the menu — gated at Player Level 7 per the existing UnlockGates table. Opens the Arcane lobby directly. Plan 5\'s faction tree later replaces this single tile with the full tree picker',
      'Campaign restrictions enforced at tower placement: allowedTowerIds, allowedFactions, noWalls (mech_wall / mil_sandbag / mil_wire), maxTowers (counts non-walls only). v1 missions 4 + 8 swap in `restriction`/`standard` archetypes for the eventual Base Defense / Attacker (Plans 11/12) — Chunk D retrofits',
      'New tests: Arcane campaign shape (10 missions, no stubs, predicate compilation, mapIds populated), registry (Arcane registered, others null), isCampaignComplete cascade. +15 unit tests',
      'Maps used are existing standard/circle maps — bespoke Arcane-tileset maps deferred to a polish pass once Chunk C ships',
    ],
  },
  {
    date: '2026-04-30',
    title: 'Campaign framework — mission archetypes, MissionRunner, sub-scene lobby (Plan 10 of progression roadmap)',
    changes: [
      'New CampaignDef + MissionDef schema in src/data/campaigns/CampaignDef.ts. Each campaign is 10 missions; each mission picks an archetype (Standard, Boss Rush, Speedrun, Frugal, Hero Duel, Bot Ally, Final Showdown, Restriction) and overrides waveCount / lives / gold / restrictions / objectives',
      'MissionArchetype catalog with 8 reusable archetypes for v1 + 3 stub entries (Base Defense / Attacker / Heist) reserved for Plans 11/12/13 — mission lobby surfaces stubs as "Coming Soon"',
      'MissionRunner singleton orchestrates mission lifecycle: builds the GameScene init data with all archetype-defaults + per-mission overrides, listens for game-end via the missionContext threaded through, evaluates star objectives (1 = win, 2 = win + objective, 3 = perfect run), persists to PlayerProfile',
      'GameScene init now accepts missionContext + mission gold/lives overrides. Mission lives override beats tutorial / modifier defaults. Gold can be additively bumped or multiplicatively scaled (frugal = 0.5x)',
      'New CampaignLobbyScreen — Preact full-screen scene per faction. Linear 10-mission card list with star ratings, locked silhouettes, archetype badges, pre-mission story modal showing intro + objective list, completion banner when all missions clear',
      'PlayerProfile.campaignProgress reshaped from { factionId → count } to { factionId → { missionIdx → stars } }. Stars are monotonic — a 2-star replay can\'t downgrade a 3-star clear. Mission N+1 unlocks when mission N earns ≥1 star',
      'New analytics: campaign_lobby_opened, mission_started, mission_completed (with stars + elapsedMs), mission_failed (atWave), campaign_completed (totalStars). Server now slices missionsByFaction / missionsByArchetype / missionFailsByFaction in summary',
      'Server per-event dim list extended with campaignFactionId + archetypeId',
      'No campaign content shipped this plan — Arcane (Plan 14) lands next',
      '+13 unit tests on archetype registry shape + campaign progress unlock cascade + monotonic stars',
    ],
  },
  {
    date: '2026-04-30',
    title: 'Tutorial extensions — economy / vs-CPU / JIT / faction briefs / Help carousel (Plan 4)',
    changes: [
      'New 4-wave Economy tutorial (`tutorial_economy`) on Hero Plains. Gentle scripted lesson — 99 lives, can\'t fail. Teaches kill gold, frontier income, and sends. Reachable from the ? Help carousel and an end-of-FTG CTA. No auto-prompt',
      'New 5-wave vs-CPU tutorial (`tutorial_vs_cpu`) — real Versus session against a balanced bot opponent. Coach marks for sends-go-to-opponent, opponent minimap, ready vote. Routes through the existing `LobbyScreen.startVsCpu` flow with `waveCount=5` cap',
      'JIT (just-in-time) lessons — 5 single-step popovers fired the first time the player encounters flying, regenerating, mage, or boss creeps, plus the first leak past their towers. Suppressed inside scripted tutorials so they don\'t collide. Idempotent via PlayerProfile flags',
      'Faction briefs expanded from a single tip line to 5 teaching steps each — identity / opener / key tower / what to avoid / how you win. 11 factions × 5 lines, terse-mechanical voice (no flavor text)',
      'New "Skip all faction briefs" toggle in the Help carousel — persisted in TutorialPersistence; suppresses every `faction:*` auto-trigger globally',
      'Replaced the old "?" track-list drawer with a 6-card How To Play carousel (Mazing / Income / Factions / Modes / Sends / Online). Plain teaching voice, ≤40 words per card. "All Tutorials →" link inside the carousel exposes the full track list for replay',
      'Rewrote the legacy `basics` walkthrough copy. Old "What\'s Different: Mazing / Income" framing dropped per user feedback that it read like marketing — now plain teaching voice. End-of-tour CTA replays the FTG instead of the old longer tutorial_match',
      'New analytics catalog: existing tutorial_track_started/completed/quit + tutorial_step_seen/completed/skipped events from Plan 1 already cover Tutorial 2 / 3 / JIT / brief telemetry — no new event types needed',
      '+14 unit tests covering Plan 4 tracks, JIT shape, faction-brief expansion, skip-all-briefs persistence, and the carousel UX',
    ],
  },
  {
    date: '2026-04-30',
    title: 'First Tutorial Game (FTG) splash + slim onboarding track (Plan 3 of progression roadmap)',
    changes: [
      'New cold-boot SplashScreen — single Welcome card with a large "Play Tutorial (~3 min)" button and a small "Skip"',
      'Splash gates the menu only when the player has never finished a guided tutorial AND never explicitly dismissed first-launch — migrated legacy players never see it',
      'New `ftg` tutorial track — slimmer than the existing `tutorial_match`. 8 steps: welcome → pick Bolt → place → mazing reveal → pick Bolt again → extend maze → start wave 1 → done. Mazing + towers ONLY, no frontier/sends/draft per the user-flagged "too much in tutorial mode" feedback',
      'Reuses TutorialMode + the existing `tutorial` map (single straight east-west corridor with generous build space)',
      'On FTG complete: `markFirstGameComplete()` sets the profile flag (so splash never re-prompts) AND grants a one-shot 200 XP bonus that crosses L1 → L2 cleanly so the player sees the unlock loop immediately',
      'Pressing Quit during FTG also returns to menu (mirrors the existing tutorial_match flow)',
      'The legacy `basics` menu walkthrough now defers to FTG — basics will not auto-fire on cold boot when first_game_complete is false. Still reachable via the Help menu (Plan 4 will tone its "What\'s Different" copy down)',
      '+10 unit tests on the FTG track shape and the markFirstGameComplete idempotency / migration paths',
    ],
  },
  {
    date: '2026-04-30',
    title: 'Player Profile + Player Level + hidden-content menu (Plan 2 of progression roadmap)',
    changes: [
      'New permanent global Player Level — distinct from the seasonal Battle Pass, drives unlocks for modes / maps / future faction tree',
      'XP curve: 200 × level per step. Standard 30 win on Normal = 150 XP. Hard +50%, Insane +100%. First-time faction +50, first-time map win +25. Defeat at wave 5+ awards a small engagement bonus',
      'Cores currency added (parallel to Shards). Earned in Career mode (Plan 15) — spent on tower-chip upgrades (Plan 16). Never sold for money',
      'Menu now hides locked modes / maps and shows a single "More at L_" teaser tile in their place. Faction list stays visible — silhouettes come with the faction tree (Plan 5)',
      'Mode unlock levels: Endless L5, Hero Defense L8, Essence (Battle) L9, Versus L10, Co-op L12, Gauntlet L14',
      'Map unlock levels: Crossroads L2, Fortress L4, Serpentine L5, Islands L6, Random L6, Gauntlet L8, Spiral L10, Siege L12',
      'Level-up modal — full-screen take-over after a game ends with the new level + unlock list. Reusable styling for future faction-unlock and achievement reveals',
      'Migration: existing players with gamesPlayed > 0 get an inferred starting level (1 game ≈ 1 level, capped at L20) + a one-shot welcome banner',
      'Every analytics event now auto-includes playerLevel / cores / shards / unlockedFactionsCount via the Plan-1 player-context hook',
      'Save format: new td_profile localStorage key, separate from td_store so a season rollover never wipes the spine of progression',
      'New analytics events: profile_initialized, profile_migrated_from_legacy, xp_awarded, level_up, unlock_revealed, menu_locked_tile_tapped',
      '+30 unit tests on the XP curve and unlock gates',
    ],
  },
  {
    date: '2026-04-30',
    title: 'Telemetry foundation (Plan 1 of progression roadmap)',
    changes: [
      'Typed analytics catalog (AnalyticsEvents.ts) — ~30 event shapes covering game lifecycle, onboarding, mode lifecycle, progression, monetization, encyclopedia, and achievements',
      'Analytics.track<E>(name, payload) typed entry point. Legacy event(type, data) preserved for back-compat',
      'Auto-attach: every event now carries platform, sessionId, ts, and (after Plan 2 lands) playerLevel + cores + shards + unlockedFactionsCount',
      'New ?debug-gated AnalyticsDebugPanel — fixed bottom-left ring buffer of the last 200 events with filter + copy-as-JSON',
      'Tutorial events wired: track_started/completed, step_seen/completed/skipped, quit. Battle Pass wired: bp_xp_awarded, bp_level_up, bp_premium_purchased, bp_reward_claimed, plus purchase_attempted/completed/failed for the BP IAP',
      'Mode lifecycle: mode_entered fires on game start, mode_exited fires on game end with durationMs',
      'Cold-boot app_boot event with viewport + touch info, menu_view fires once per menu mount',
      'Server (Cloudflare Worker): per-event dimension list extended (trackId, stepId, factionId, route, unlockType, category, id, currency); summary + history endpoints surface 17+ new event types and tutorial-funnel + faction-unlock + achievement + purchase-mix breakdowns',
    ],
  },
  {
    date: '2026-04-23',
    title: 'Circle Co-op late-game rebalance',
    changes: [
      'Coop creep HP ramps +3.5% per wave on top of existing scaling — team DPS was outpacing creep HP late',
      'Kill gold in coop multiplied by 0.7 (was 1.0). Team total = 70% of solo, each player share = 35% after the 50/50 split',
      'Frontier income multiplier = 1.5× in coop — applies to passive income, per-wave bonuses, overcharge bursts, and grow harvests',
      'Solo / 1v1 / endless scaling is unchanged — every knob defaults to a no-op outside coop',
    ],
  },
  {
    date: '2026-04-23',
    title: 'CPU brain: must have a fighting tower before buying frontier/sends',
    changes: [
      'FIX: BalancedBrain rolled meta-economy at the top of every between-waves tick — on wave 0, the 70% commit chance meant the bot could blow its budget on frontier before placing any tower',
      'Added a gate: meta economy (frontier + sends) only fires once the bot owns at least one non-wall tower — a wall-only zone has no DPS either, so walls alone don\'t count',
    ],
  },
  {
    date: '2026-04-23',
    title: 'Jackpot boss resistance tuned: halve → quarter',
    changes: [
      'Follow-up to the earlier Gambler pass — ×0.5 boss multiplier still felt too generous in practice',
      'Kill slice now ×0.25 vs bosses. Gambler: 4%/1% (was 4%/2%). Oblivion: 15%/3.75% (was 15%/7.5%)',
      'OpponentSimulation shadow sim mirrors the same quartering for 1v1 CPU',
    ],
  },
  {
    date: '2026-04-23',
    title: 'Circle Co-op roster → DOM panel',
    changes: [
      'Roster (kills, gold, towers, lives, timer) moved from Phaser Text to a Preact component so font sizes scale on phone via UIScale',
      'New GameUIStore.circleRoster snapshot rewritten each frame; shallow-equal check skips re-renders when nothing changes',
      'Top-right positioning accounts for zoom buttons on desktop; phone hugs the right edge',
    ],
  },
  {
    date: '2026-04-23',
    title: 'Endless mode bug fixes',
    changes: [
      'FIX: faction rotation at wave 10/20/... forgot to rebind creep sprites — new faction creeps rendered with the prior faction\'s textures',
      'FIX: faction rotation used Math.random(), so host + joiner diverged in multiplayer Endless. Now seeded from sharedSeed ^ waveNum',
      'FIX: UpcomingWaves snapshot ran before the append-more-waves block, so newly generated waves didn\'t appear until the next clear',
    ],
  },
  {
    date: '2026-04-23',
    title: 'Gambler balance: 4% instant kill, quartered vs bosses',
    changes: [
      'Gambler jackpot.killChance dropped from 8% to 4% — 15g + fast fire rate made the 8% roll too cheap',
      'NEW universal boss resistance on jackpot: kill chance ×0.25 when target.isBoss. Gambler: 4%/1%. Oblivion: 15%/3.75%',
      'Miss chance unchanged — no "please whiff" perk for bosses',
      'HitTarget interface gained isBoss. Shadow sim in OpponentSimulation mirrors the same quartering for 1v1 CPU',
    ],
  },
  {
    date: '2026-04-22',
    title: 'Multiplayer + random-faction bug sweep',
    changes: [
      'FIX 1v1: client could send T2/T3 sends before unlock wave — receiver now re-validates unlockWave and drops locked messages',
      'FIX 1v1: flying sends walked the maze for the receiving host — SendManager now supports a flying path and routes creepType flying through it',
      'FIX Circle Co-op: host + client saw different kill counts for the same creep — new creep_killed broadcast syncs per-player kill totals across all peers',
      'FIX Circle Co-op: CPU players missing from the human peer\'s roster — clients now sync playerCount + botSlots from circle_game_start',
      'NEW Circle Co-op: shared economy — every kill splits 50/50 between the killer and the spawn-owner (whoever\'s zone/send the creep came from). Creep carries spawnOwnerIndex; DeathHandler credits each share on every peer via the new broadcast.',
      'FIX Random faction: Razor Bramble could roll into the random tower pool — pool source changed from TOWER_TYPES to Factions[*].towerIds so branch-only towers are excluded',
    ],
  },
  {
    date: '2026-04-22',
    title: '1v1 Versus: CPU opponent runs real per-tower combat',
    changes: [
      'REWRITE: OpponentSimulation now does per-tower-per-creep combat instead of a DPS smear — picks targets, fires on cooldown, applies splash/slow/root/poison',
      'Per-hit and per-kill gold routed into the CPU bot economy — void siphon, gambler jackpot, damage variance (spike/oblivion), and infernal soul drain all credit the bot correctly',
      'Adjacency buffs (Nature Blossom) stack onto neighbour tower damage + fire rate for the CPU, matching the human side',
      'Tower-aura DoTs (Spore) poison creeps in radius each tick',
      'Branched towers (Bramble → Razor) now resolve the target TowerType when `tower_upgraded.branch` syncs, so the sim keys off the correct stats',
      'Simplifications: no projectile travel time (hits resolve instantly), always-first targeting, no creep armor resistances. The sim drives economy + minimap only, never user-visible numbers',
    ],
  },
  {
    date: '2026-04-22',
    title: 'Nature dock hotkeys realigned + Razor re-coloured',
    changes: [
      'FIX: Nature dock hotkeys were scrambled — viper was on 8, blossom on 3, sunroot on 9. Now: bramble 1, root 2, viper 3, blossom 4, spore 5, sunroot 6, vine 7, elder 8',
      'Razor Bramble palette swapped from pink/magenta to blood red + bone white so it no longer reads as Blossom at game-icon scale',
      'Veins are crimson #cc2222, fangs get bone-white tips with blood droplets, base pooling is dark blood red',
    ],
  },
  {
    date: '2026-04-22',
    title: 'Grove Viper thickened — chunky rope, not a wire',
    changes: [
      'Snake body bumped from 2 cells to 3/4/5 per level with orientation-aware cross-sections (vertical stripe for walk-right, horizontal for walk-up/down)',
      'Dark outline pixels guaranteed on both edges every frame so the silhouette reads against any background',
      'L1 palette shifted to bark browns so a juvenile viper contrasts against grass tileset instead of blending in',
      'Denser segment sampling (10/12/14 body cells per level) prevents visible gaps in the body curve',
    ],
  },
  {
    date: '2026-04-22',
    title: 'Debug logs gated behind ?debug QSP',
    changes: [
      'New DebugFlags module reads `?debug` from the URL',
      'Wave-sync console logs (stuck creeps, wave cleared, Next Wave ignored) and endless-mode rotation logs now only print when debug is on',
      'Normal play is quiet — visit `localhost:5173/?debug` to re-enable diagnostics when investigating a stuck-wave report',
    ],
  },
  {
    date: '2026-04-22',
    title: 'Mire Dart → Grove Viper: slithering snake replaces the frog',
    changes: [
      'REPLACED Mire Dart frog with Grove Viper snake. Same mobile-unit slot, but slither animation (sine-wave body undulation per frame) + twin-fang strike lunge instead of hop + tongue-lash.',
      'Stats: 40g, 5 dmg, 2.5 range, 950ms fireRate, moveSpeed 100, engageRange 1.8, poison 6%/s over 4.5s. Upgrades scale DPS and strike range further.',
      'Three life stages: L1 slim sage juvenile, L2 diamond-back viper with forked tongue, L3 dark matriarch with cobra hood flare, slit pupil, rattle tail, and red diamond accents.',
      'Tower dock icon redrawn as a coiled cobra in ready-to-strike pose. Attack visual is a twin-fang lunge with green venom splash + two red puncture marks at the bite site.',
      'Renamed `nature_dartfrog` → `nature_viper` across TowerTypes/Factions/SpriteManager/skin-editor/lore; `dartfrog_mobile.png` replaced with `viper_mobile.png`.',
    ],
  },
  {
    date: '2026-04-22',
    title: 'Divergent upgrade paths — Bramble forks into Hedge or Razor Bramble',
    changes: [
      'NEW: Bramble Hedge now branches at L2 — choose "Hedge" (wall-focused, caps L3) or "Razor Bramble" (DPS-focused, caps L4 with 15 dmg @ 220ms)',
      'Tower info panel shows both buttons side-by-side with per-option stat previews; picking one commits (sell to switch)',
      'Razor Bramble has its own dedicated tower art column, projectile, and skin-editor slot — treated as a separate tower for skins',
      'CPU bots reason about branches via `BotDecision.upgrade.branch` — Balanced brain promotes Bramble → Razor when budget allows',
      'Multiplayer protocol: `tower_upgraded.branch` synced so Versus and Circle Co-op peers see the same art / ladder',
      'Nature sprite sheets expanded to 9 columns (576×1536) with matching _autumn variants regenerated',
      'Razor Bramble art rewritten: bark grain, red vein network, serrated blade teeth, tooth-crown (3/5/7 fangs by level), barbed edges, moss+blood base detail, state overlays',
      'Thornweaver redrawn: L1 juvenile sage blob, L2 striped adolescent with fangs + thorn ridge, L3 dark matriarch with carapace spine + claw tips + eye cluster — each level now a distinct creature',
    ],
  },
  {
    date: '2026-04-22',
    title: 'CPU opponent in 1v1 + bots play the meta economy',
    changes: [
      'NEW: "VS CPU" button in the Versus 1v1 lobby — play against a local bot with no signaling or second browser',
      'Reuses the same brain-driven bot AI that Circle Co-op uses (renamed CircleBotAI → BotAI)',
      'CPU opponents place towers on a private grid; its moves show up on your opponent minimap like a real remote peer',
      'Bots can now UPGRADE their towers (best-coverage non-wall DPS) and SELL them (weakest wall when zone is saturated)',
      'Bots buy SENDS at you and invest in FRONTIER buildings between waves — CPU pressure + compounding income',
      'Sends from you actually LAND on the CPU now (previously cosmetic against a simulated peer)',
      'Circle Co-op: gold/towers/kills now break out per-player on the victory/defeat screen, including CPU bots',
      "Co-op tower panel hides Upgrade/Sell for another player's tower (you can still inspect stats)",
      'Co-op waves spawn 3–4× faster to match the team-size creep-count scaling (no more trickle)',
      'Tower info panel shows live effective stats (post-aura DMG/SPD/RNG in green, with the pre-buff number struck through)',
      'New CPU_BRAIN.md doc at the repo root — walkthrough of the bot decision state machine (driver cadence, phase selection, meta pass)',
      'Bots now collect per-hit gold from their own towers (Void gold_on_hit / jackpot). Previously all tower gold dumped into the human\'s shared pool',
      'FIX: "Next Wave" button could get permanently stuck greyed after a rejected tower placement (stale cached paths left over from the rollback)',
      'Nature faction reshuffled to 8 towers: Thorn removed, Bramble Hedge takes the cheap-DPS slot (12g, 5-level scaling thornbrush), plus Thornweaver mobile poison spider (45g) and Sunroot splash DPS (140g)',
      'Nature spritesheets rebuilt: new tower/projectile art for Bramble, Thornweaver, Sunroot, plus a proper Thornweaver mobile walk-cycle sheet. Autumn skin variants regenerated to match.',
      'Skin editor (skin-editor.html) now shows the new 8-tower Nature roster — Bramble has dense leafy detail (dappled body, branch silhouettes, clustered leaves, berries at L5) instead of a solid green slab.',
      'REPLACED Thornweaver spider with Mire Dart poison-dart frog: hops in 4-frame arcs instead of sliding, tongue-lashes targets for poison, three distinct life stages (pale hatchling → yellow-striped dart → dark spotted matriarch with gnarled tongue and bulging throat sac)',
      'Mire Dart stats: cheaper (40g vs 45g), weaker direct hit (4 vs 8 dmg) but stronger venom (5%/s 4s vs 3%/s 3s) — the dart IS the damage',
      'Renamed `nature_spider` → `nature_dartfrog` across TowerTypes/Factions/SpriteManager/skin-editor/lore; old `spider_mobile.png` replaced with `dartfrog_mobile.png`',
      'Mobile units now have signature attacks: Spider spits a venom gob that splatters toxic droplets (scales with level), Swarmling rakes with chitin-scratch lines. Rifleman/Commander/Brawler/Heavy keep their existing look.',
      'All PNGs re-baked from the TSX sprite modules via the full browser pipeline so editor previews and in-game textures match exactly.',
      'Nature CPUs no longer waste gold on Blossom-as-maze: fixed role classifier so adjacency/buff towers are correctly "aura" not "wall"',
      'Void Rift now bites a little: 2/3/4 damage across levels on top of the teleport (was 0 at all levels)',
    ],
  },
  {
    date: '2026-04-17',
    title: 'Celestial + frontier fixes',
    changes: [
      'Celestial Acolyte / Absolution life-on-kill actually procs now (was silently failing on a sentinel timing bug)',
      'Celestial Sanctuary absorbs leaks as advertised (Standard: blocks 1 life per charge; HD: 5%-base-HP damage shield drained on base hits)',
      'HD mode: life_on_kill heals base by 5% of max HP instead (mirrors +1 life in Standard)',
      'Destroyed frontier buildings now fully disappear — map doodad gone, panel entry gone (no more ghost "DESTROYED" rows)',
    ],
  },
  {
    date: '2026-04-17',
    title: 'Creep inspector moved to DOM',
    changes: [
      'Creep info panel (click a creep) migrated from Phaser to Preact',
      '60Hz refresh with diff-notify — Preact only re-renders on real stat changes (HP ticks, armor shred, effect expiry)',
      'HP gradient bar on top of the panel — green → amber → red',
      'Desktop: collapsible sidebar panel with faction-colored title and boss badge',
      'Phone: floating card shared slot with tower info (already mutually exclusive)',
    ],
  },
  {
    date: '2026-04-16',
    title: 'Factions rename + engine refresh',
    changes: [
      'Renamed Tower Defence → FACTIONS. New app-startup splash: "FACTIONS by Running Man Games"',
      'Background icon preheat eliminates the Store first-open hang on mobile — sprite cache warms during the splash',
      'Faction-tinted placeholders in SkinPreview while icons extract (edge case: opening Store faster than preheat)',
      'Mobile fix: tower info card no longer hides behind the status bar (dynamic measurement)',
      'Infernal Fiend mobile sprite 404 fixed — filename now derived from sheetKey, not towerId',
      'Upgraded Phaser 3 → 4 (Caladan). Explicit Phaser imports everywhere, no more window.Phaser global',
      'In-game changelog migrated from Phaser scene to DOM, keyed by date instead of version',
    ],
  },
  {
    date: '2026-04-11',
    title: 'Endless Mode + Streamlined Menu',
    changes: [
      'NEW MODE: Endless — infinite scaling, play until you fall',
      'Random creep faction every 10 waves, boss every 10 waves',
      'HP scales cubically beyond wave 50 — gets brutal',
      'Game over shows "Survived X waves" — no victory, only glory',
      'Sprint/Standard/Marathon merged into one Standard mode',
      'Wave count picker: Quick (15), Standard (30), Extended (100)',
      'Menu streamlined from 8 to 7 mode cards',
    ],
  },
  {
    date: '2026-04-11',
    title: 'Custom Maps',
    changes: [
      'NEW: Custom Maps — create, save, and play your own maps',
      'Custom Maps menu: browse saved maps, import from clipboard, open map editor',
      'Maps saved to browser localStorage — persist between sessions',
      "Multiplayer: host's custom map auto-synced to all players via WebRTC",
      'Works with Versus 1v1 and Circle Co-op lobbies',
      '93 structures with detailed pixel art across all 11 factions',
      'Terrain tile improvements: toned-down void, fixed lava/water/thought pool merging',
      'Harmonic orchestra seating terrain, infernal terrain less intense',
      'Automated sprite export via Puppeteer (node scripts/export-sprites.mjs)',
    ],
  },
  {
    date: '2026-04-10',
    title: 'Animated Structures + Map Editor',
    changes: [
      '90 animated large structures across all 11 factions (8-10 per faction)',
      'Structures animate at 1.5 fps: flames flicker, gears rotate, portals swirl, crystals pulse',
      'Gauntlet maps redesigned with faction-themed structure placements',
      'Structure sprites bake faction ground tiles — seamless terrain blending',
      'Visual map editor at /editor.html: paint terrain, place structures, export JSON',
      'Maps now stored as JSON files — easy to edit and share',
    ],
  },
  {
    date: '2026-04-09',
    title: 'Faction Gauntlet',
    changes: [
      'NEW MODE: Faction Gauntlet — 100 waves across 10 faction homeworlds',
      '10 unique themed maps with custom pixel art terrain and animated tiles',
      'Each faction homeworld: crystal caverns, iron foundry, ancient grove, rift dimension, warzone outpost, hive tunnels, data grid, hellscape, sky citadel, mind palace, concert hall',
      'Preview screen shows full randomized stage order before starting',
      'Stage transitions: fade to black, faction banner, new map loads',
      'Frontier + send income persist, towers reset, lives reset to 10 per stage',
      'Stage scaling: HP 1x-4x, speed 1x-1.5x, extra count ramp',
      'HUD shows current stage and faction during gameplay',
    ],
  },
  {
    date: '2026-04-09',
    title: 'Creep Sprites + Terrain + Zoom',
    changes: [
      'Creep sprites for all 11 factions — 176 unique creatures with walk + death animations',
      'Creep Faction Select: choose which enemy faction you face',
      'Terrain system: themed auto-tiled terrain for all maps (mountain, water, trees, stone, lava)',
      'Ground doodads: bushes, flowers, pebbles, mushrooms scattered on walkable tiles',
      'Tower targeting priority: snipers target strongest, frost targets fastest, etc.',
      'Desktop zoom: scroll wheel + middle-click pan + buttons',
      'Mobile camera: pinch zoom, elastic bounds, responsive tower bar',
      'UILayer system: eliminated camera filter bugs',
      'PanelBase: reusable sidebar panel class',
      'Multiplayer signaling server (Cloudflare Workers)',
      'Analytics dashboard with world map',
    ],
  },
  {
    date: '2026-04-07',
    title: 'Sprite Art + Balance',
    changes: [
      'Pixel art sprites for all 11 factions — towers, projectiles, and heroes',
      'Per-level tower art: towers visually evolve as they upgrade (up to 6 levels)',
      'Tower picker shows sprite icons instead of text labels',
      'Hero select shows sprite portraits (desktop + phone)',
      'Encyclopedia displays tower and hero sprite art',
      'Mobile unit walk-cycle sprites: Rifleman, Brawler, Tank, Commander, Swarmling, Fiend',
      'Heavy Gunner → Tank: slower (45 speed), longer range (4.5-6 tiles), AoE explosive shells',
      'Brood Mother: commander_aura buffs Swarmlings +20% DMG +15% AS within 6 tiles',
      'Firewall: 35 DPS + 65% slow through beam',
      'Meteor: true ground-targeting — hits where the creep was, not where it moved',
      'Railgun: projectile travels to map edge, damages creeps as the beam passes',
      'Arcanist renamed to Mage',
      'Hero Defense tomes: XP Tome (100g), Stat Tome (250g+), Interest Tome (2%→5%)',
      'Mobile: zoom bounds scale with zoom level, pause menu centers on screen',
      'Send panel expanded for T2 sends, event log bottom-anchored',
      'Creep info panel properly sized for shield/effects display',
    ],
  },
  {
    date: '2026-03-21',
    title: 'Mobile Phone Support',
    changes: [
      'Pinch-to-zoom (1x–3x) + drag-to-pan on phone — camera starts at 1.8x zoom',
      'Touch controls: tap to place towers, drag to pan, pinch to zoom',
      'GameControlBar: touch buttons for wave/speed/pause + ability buttons (Q/W/E/R/T)',
      'Touch clicks deferred to pointerup — panning never accidentally places towers',
      'Full-screen sidebar overlay on phone with larger close button',
      'Smaller tower buttons (42px), responsive menu/faction/hero select scenes',
      'Hero select: single-card carousel with prev/next navigation on phone',
    ],
  },
  {
    date: '2026-03-20',
    title: 'Hero Defense Overhaul',
    changes: [
      '11 heroes (up from 3): Paladin, Ranger, Berserker, Necromancer, Monk, Engineer, Duelist, Druid',
      'Random draft: 3 heroes offered per game, reroll available',
      'Each hero belongs to a faction — picking a non-random faction guarantees that hero',
      'Hero leveling (uncapped): XP from arena kills, choose stat or ability upgrades per level',
      'Ability upgrades: [+] buttons next to Q/W/E/R — each gives +20% damage/effects, -5% CD',
      'Ultimate abilities (R key): one per hero, unlocks at level 6, long cooldown',
      'Floating damage numbers: color-coded hits, crits, heals, ability damage, level ups',
      'Ability VFX: AoE rings, dash trails, teleport flashes, meteor impacts, lightning bolts',
      'Visual targeting mode for ground abilities (Blink) — preview circle + range ring',
      'Arena creep waves: 3-6 creeps spawn per TD wave (halved on boss waves)',
      'Elite enemies at waves 10/20/30: Shield Guardian, Base Charger, Necromancer',
      '3 accessory slots (up from 1): 15 accessories total, rotating shop every 5 waves',
      'New AoE accessories: Cleave Axe, Inferno Blade, Tempest Hammer — attacks splash in radius',
      'Tower assists: leaked creeps enter arena with current HP (tower damage carries over)',
      'Melee heroes buffed: +100-150 HP and innate armor (2-8) varying by hero',
      'Healer diminishing returns: stacked heals halved per source, healers receive only 10%',
      'Economy rebalanced: reduced kill gold, wave income, and arena rewards',
      '2% interest on gold at end of each wave',
      'Stat accessories: War Gauntlet (+dmg), Heart of Iron (+HP), Rapid Quiver (+AS%), Hawk Eye (+range)',
      'Faction heroes: each hero belongs to a faction, guaranteed in draft if you pick that faction',
      'Sidebar shows attack speed instead of move speed',
      'Heroes encyclopedia page with carousel browser',
    ],
  },
  {
    date: '2026-03-20',
    title: 'Procedural Random Maps',
    changes: [
      'New "Random" map in the map picker — procedurally generated from a seed',
      '6 layout templates (classic, dual entry, siege, gauntlet, diagonal, corridor)',
      'Terrain features: lakes, ridges, pillars, walls, islands, boulder clusters',
      'Difficulty-linked density: Easy = open, Insane = cramped with NoBuild zones',
      'Daily seed toggle: same map for everyone that day (seed = YYYYMMDD)',
      'Versus uses shared seed — both players get identical random maps',
      'Seed displayed in top-right corner during gameplay',
    ],
  },
  {
    date: '2026-03-19',
    title: 'Difficulty Scaling, Send Tiers & Bug Fixes',
    changes: [
      'Send cost scaling: costs rise +10% per 5 waves, income rewards scale slightly to compensate',
      'Tier 2 sends: Healer (w10+), Shielded (w10+), Flying (w15+), Regen (w20+) — hotkeys 1/2/3/4',
      'Send panel updates each wave with current costs and unlock status',
      'Fixed DoT/beam rounding bug: Virus, burn, and Firewall beam were dealing 0 damage at 60fps',
      'Quadratic HP scaling: late-wave creeps are much tougher (wave 20: 340 HP, wave 30: 620 HP)',
      'Themed late-wave compositions: healer+tank packs, speed rushes, regen DPS checks, flying bypasses',
      'Kill gold decays over time (5g → 4g → 3g → 2g floor) to prevent income snowball',
      'New creep type: Regenerator — heavy armor, 2% HP/s regen, appears wave 25+',
      'New regeneration trait with green pulse visual effect',
      'Hard difficulty retuned: toughness 2.0×, count 1.6×, speed 1.2×, gold 0.6×',
      'New Insane difficulty: 3.5× toughness, 2× count, 1.35× speed, 0.4× gold. Good luck.',
      'Insane extras: boss damage-cap shields, armored regen, 45% evasion, 5% regenerator regen',
      'Hard-mode bosses now regenerate 1% HP/s',
      'Faster late-wave spawns (floor lowered to 150ms)',
    ],
  },
  {
    date: '2026-03-18',
    title: 'Responsive Scaling & Tablet Support',
    changes: [
      'Tablet layout: sidebar becomes a collapsible overlay with hamburger toggle',
      'Touch input: long-press (500ms) to sell towers, tappable Upgrade/Sell buttons',
      'Tappable Start Wave and Speed buttons in the status bar',
      'Dynamic canvas sizing — game area fills available width on smaller screens',
      'All menus and scenes adapt to the active canvas width',
    ],
  },
  {
    date: '2026-03-18',
    title: 'Circle Co-op + Hero Combat + Menu Redesign',
    changes: [
      'New multiplayer mode: Circle Co-op — 2-4 players on one shared map',
      'Creeps loop through all player zones; shared lives, individual gold',
      '3 new circle maps: 2P (halves), 3P (Y-sectors), 4P (quadrants)',
      'Zone overlay, player roster panel, wave sync with ready votes',
      'Individual gold: kill credit tracks which tower dealt the killing blow',
      'Periodic tower sync every 5s reconciles missed placements between players',
      'Lobby: joiners see their player index, all players notified of new joins',
      'Hero Defense: arena creeps now aggro and attack the hero (240px range)',
      'Hero Defense: creeps park at base and repeatedly attack it (10k base HP)',
      'Hero Defense: 10x creep waves with faster spawns for arena pressure',
      'Hero Defense: ranged heroes (Arcanist) fire visible projectiles',
      'Harmonic: conduit-linked aura towers re-emit inherited buffs to neighbors',
      'Menu redesign: 2x3 card grid for all 7 modes with color-coded accents',
      'Autoplay: press A or click [A] AUTO to auto-start waves',
    ],
  },
  {
    date: '2026-03-18',
    title: 'Hero Defense Mode',
    changes: [
      'New game mode: Hero Defense — leaked creeps enter a hero arena',
      'Split-screen layout: hero arena (top) + smaller TD grid (bottom)',
      '3 heroes: Warden (tank), Arcanist (mage), Shadow (assassin)',
      'Click-to-move hero micro, Q/W/E abilities with cooldowns',
      'Hero item shop: Weapon, Armor, Boots with 3 upgrade tiers each',
      'Arena creeps fight back — aggro, chase, and attack the hero',
      'Base HP replaces lives — creeps past the hero damage the base',
      'Hero death/respawn: 10s timer, full HP on respawn',
      'Ranged heroes fire projectiles, melee heroes deal instant damage',
      'Creeps that reach the base park and attack it repeatedly',
      '10x creep waves flood the arena, 10% kill gold to balance',
      '10,000 base HP replaces lives, hero heals 20% on wave clear',
      'Hero select screen with stat cards and ability descriptions',
    ],
  },
  {
    date: '2026-03-18',
    title: 'GameMode Interface',
    changes: [
      'Pluggable GameMode system: each mode is a self-contained class',
      'StandardMode owns sends, frontier panel, and frontier actions',
      'BattleMode owns essence panel, generators, and essence sends',
      'Frontier actions (overcharge/dig/harvest) moved from GameScene into StandardMode',
      'Fixed: eventLog created before game mode init (was null)',
      'Fixed: versus reference now wired into game mode context',
      'GameScene reduced from ~1200 to ~1070 lines',
    ],
  },
  {
    date: '2026-03-18',
    title: 'Dual Economy & Architecture',
    changes: [
      'Battle mode: Dual Economy with Gold + Essence resources',
      'Essence generators: buy with gold, produce essence in real-time',
      'Sends cost essence instead of gold — compound growth loop',
      'GameScene decomposed: TowerManager, CreepManager, WaveController',
      'Pluggable leak/death handlers for future game modes',
      'ResourceManager: N-resource system with real-time ticking',
    ],
  },
  {
    date: '2026-03-18',
    title: 'New Factions & Maps',
    changes: [
      'Harmonic faction: stacking aura network with Conduit linking',
      'Manual Conduit: press L to link/unlink aura towers',
      'Distinct aura colors: red (damage), green (rate), blue (range), magenta (crit)',
      'Maps reworked: mountains, lakes, rivers, canyons',
      '5 new maps: Serpentine, Islands, Gauntlet, Spiral, Siege',
      'Encyclopedia: Factions carousel, Tower carousel, Creep cards',
      'In-app Changelog viewer with full history',
      'Version SHA on menu screen',
    ],
  },
  {
    date: '2026-03-17',
    title: 'Harmonic & Encyclopedia',
    changes: [
      'Harmonic faction: aura network with stacking damage/rate/range/crit auras',
      'Conduit tower links aura towers and shares their effects at 70%',
      'Encyclopedia: browse all towers, creeps, and frontier buildings',
      'In-app changelog with scrollable history',
      'Version SHA displayed on menu screen',
      'Maps reworked: mountains, lakes, rivers instead of NoBuild zones',
    ],
  },
  {
    date: '2026-03-17',
    title: '6 New Factions',
    changes: [
      'Spawn Aliens: extreme fire rates, Swarmling mobile units, Brood Mother',
      'Cypherpunk: Firewall beams, Virus spread, Backdoor hack (walk backward)',
      'Infernal: Imp (expires), Hellfire (decays), Fiend (kamikaze explode)',
      'Celestial: life gain on kill, Ward mutes mages, Sanctuary absorbs leaks',
      'Psionic: true damage ignoring armor, Mesmer confusion, fear aura',
      'Military faction with mobile units (Rifleman, Brawler, Heavy, Commander)',
      'Mobile unit balance nerfs across all factions',
    ],
  },
  {
    date: '2026-03-16',
    title: 'Multiplayer',
    changes: [
      'P2P WebRTC multiplayer — no server required',
      'Manual SDP exchange via clipboard (host/join)',
      'Sends go to opponent as extra creeps in their game',
      '60s first wave / 30s subsequent countdown with ready vote',
      'Opponent minimap — click to swap full view with simulated creeps',
      'In-game chat (ENTER key), host controls game speed',
      'Mirrored waves via shared seed, wave sync protocol',
      'Disconnect detection — continues as solo game',
    ],
  },
  {
    date: '2026-03-16',
    title: 'Creep Variety & Difficulty',
    changes: [
      'Difficulty system: Easy/Normal/Hard/Insane with per-creep-type scaling',
      '7 new creep types: Group, Splitter, Shielded, Evasive, Flying, 4 Mage types',
      'Flying creeps bypass maze entirely (straight line to exit)',
      'Shielded creeps: max 1 damage per hit until shield breaks',
      'Confused creeps walk backward, Muted creeps lose abilities',
      'NoBuild terrain: walkable but unbuildable cells',
      'Boss leak costs 5 lives instead of 1',
    ],
  },
  {
    date: '2026-03-16',
    title: 'Tower Expansion',
    changes: [
      'Asymmetric faction sizes: Mechanical 8, Arcane 7, Nature 6, Void 5',
      'Cost scaling from 10g starters to 900g ultimates',
      'Per-tower upgrade design (0 to 5 levels per tower)',
      '4 ultimate towers: Titan Cannon, Arcane Nova, Elder Treant, Oblivion',
      'Random faction: 6 towers rotate each wave from all pools',
      'Creep inspection: click to see HP, armor, status effects',
      'Tower hover tooltips with full stat breakdown',
    ],
  },
  {
    date: '2026-03-16',
    title: 'Trait System',
    changes: [
      'All tower/creep behaviors are composable traits',
      'Handler registry with 5-phase resolution pipeline',
      'Removed all hardcoded ability if/else chains',
      'Abilities scale with tower level automatically',
      'Location-based projectiles for AoE towers',
      'Tracking projectiles accelerate to always catch targets',
    ],
  },
  {
    date: '2026-03-16',
    title: 'UI & Economy',
    changes: [
      'Left sidebar: Upcoming Waves, Sends, Frontier, Event Log',
      '3-mode selection: Build / Inspect / None',
      'Frontier buildings with faction mechanics (overcharge, dig, grow, gamble)',
      'Send system with Z/X/C/V hotkeys and adaptive spawning',
      'Income display, pause menu, game speed control (TAB)',
      'Score screen with tower DPS tables and economy breakdown',
    ],
  },
  {
    date: '2026-03-16',
    title: 'Foundation',
    changes: [
      'Grid-based maze building with A* pathfinding',
      '4 base tower types, 3-level upgrades, status effects',
      'Armor/damage type system (physical/magic vs light/medium/heavy)',
      '3 match modes: Sprint (15w), Standard (30w), Marathon (endless)',
      '4 original factions: Arcane, Mechanical, Nature, Void',
      'Draft modifiers: Gold Rush, Glass Cannon, Rapid Fire, etc.',
      '3 maps: Plains, Crossroads, Fortress',
    ],
  },
];

export function ChangelogScreen() {
  return (
    <>
      <Header title="CHANGELOG" back={() => UIBridge.show('menu')} rightContent={<ShardBadge />} />

      <div class="ui-section changelog-list">
        {ENTRIES.map((e, i) => (
          <div key={i} class="changelog-entry">
            <div class="changelog-entry-header">
              <span class="changelog-entry-date">{e.date}</span>
              <span class="changelog-entry-title">{e.title}</span>
            </div>
            <ul class="changelog-entry-bullets">
              {e.changes.map((c, j) => <li key={j}>{c}</li>)}
            </ul>
          </div>
        ))}
      </div>
    </>
  );
}
