/**
 * HumanReplayBrain — proposes actions from a library of captured
 * winning human matches. Becomes the 11th proposer in
 * LearningBrain so the regressor can score human-style decisions
 * at inference (not just bot-brain proposals). Without a brain
 * that actually emits the captured actions, the human-trained
 * tree paths in the model are unreachable — this brain bridges
 * that gap.
 *
 * Source data lives at `learning/captures.json`, regenerated by
 * `scripts/build-captures.mjs` from `ml/captured/*.jsonl`. The
 * file contains one record per captured turn (only winning
 * matches). Each record has:
 *   { matchId, turnIdx, faction, wave, stateFeatures, decisionRaw }
 *
 * decisionRaw lets us re-emit the actual action: kind, col, row,
 * towerId for places. Legacy captures (pre-decisionRaw) have
 * col/row null — we substitute the best-coverage candidate cell
 * at runtime.
 *
 * Decision algorithm per decide():
 *   1. Filter captures by faction.
 *   2. Compute state-feature L2 distance to each captured state,
 *      with a wave-match bonus (we don't want a wave-1 capture
 *      proposing for wave 18).
 *   3. Pick the nearest-state captured turn.
 *   4. Translate its action to the current ctx (re-anchor cell if
 *      the captured cell isn't a current candidate).
 *   5. Return the BotDecision.
 *
 * Falls back to skip if no captures are loaded for the faction.
 */
import { BotBrain, BotContext, BotDecision, Cell, registerBrain } from '../BotBrain';
import { TOWER_TYPES, getTowerType } from '../../../data/TowerTypes';
import { extractStateFeatures } from '../learning/FeatureExtractor';
import { PathPoint } from '../../Pathfinding';
import { pathCellsWithinRange } from '../MazePlanner';
import capturesData from '../learning/captures.json';

interface CapturedTurn {
  matchId: number;
  turnIdx: number;
  faction: string;
  wave: number;
  stateFeatures: number[];
  decisionRaw: {
    kind: 'place' | 'upgrade' | 'sell' | 'send' | 'frontier' | 'skip';
    col?: number | null;
    row?: number | null;
    towerId?: string;
    branch?: string;
    sendOptionId?: string;
    buildingId?: string;
  };
}

const ALL_CAPTURES: CapturedTurn[] = capturesData as CapturedTurn[];

export class HumanReplayBrain implements BotBrain {
  readonly name = 'HumanReplay';
  private factionCaptures: CapturedTurn[] = [];

  init(ctx: BotContext): void {
    this.factionCaptures = ALL_CAPTURES.filter(c => c.faction === ctx.faction);
  }

  decide(ctx: BotContext): BotDecision {
    if (this.factionCaptures.length === 0) return { kind: 'skip' };

    const stateF = extractStateFeatures(ctx);
    const nearest = findNearest(stateF, ctx.wave, this.factionCaptures);
    if (!nearest) return { kind: 'skip' };

    return translate(nearest.decisionRaw, ctx);
  }
}

/** L2 distance over state features, with a heavy penalty for wave
 *  mismatch so wave-1 captures don't propose for wave 19. */
function findNearest(
  stateF: number[], wave: number, captures: CapturedTurn[],
): CapturedTurn | null {
  let best: CapturedTurn | null = null;
  let bestScore = Infinity;
  for (const cap of captures) {
    const cf = cap.stateFeatures;
    const minLen = Math.min(stateF.length, cf.length);
    let d = 0;
    for (let i = 0; i < minLen; i++) {
      const dx = stateF[i] - cf[i];
      d += dx * dx;
    }
    // Add wave penalty — same wave costs 0; off-by-2 costs ~0.5;
    // off-by-10 costs ~12 (dominates the typical L2 of ~1).
    const waveDelta = wave - cap.wave;
    d += waveDelta * waveDelta * 0.12;
    if (d < bestScore) { bestScore = d; best = cap; }
  }
  return best;
}

/** Convert a captured decisionRaw to a runtime BotDecision. The
 *  captured cell may not be in the current match's candidateCells
 *  (different map seed → different paths), so we re-anchor by
 *  finding the nearest candidate cell. Legacy captures with
 *  null col/row pick the best-coverage candidate for the towerId. */
function translate(raw: CapturedTurn['decisionRaw'], ctx: BotContext): BotDecision {
  switch (raw.kind) {
    case 'place': {
      if (!raw.towerId) return { kind: 'skip' };
      const type = TOWER_TYPES[raw.towerId];
      if (!type) return { kind: 'skip' };
      if (ctx.budget < type.cost) return { kind: 'skip' };
      const cell = pickPlacementCell(raw.col ?? null, raw.row ?? null, type, ctx);
      if (!cell) return { kind: 'skip' };
      return { kind: 'place', col: cell.col, row: cell.row, type };
    }
    case 'upgrade': {
      if (raw.col == null || raw.row == null) {
        // No specific target — fallback: upgrade any tower we own
        // matching the captured tower type. (Legacy captures lose
        // cell coords; we don't propose blind upgrades.)
        return { kind: 'skip' };
      }
      // Find an owned tower matching the captured location — try
      // exact, then nearest. Captured upgrades are sparse signal so
      // we don't aggressively re-anchor.
      const owned = pickOwnedNear(raw.col, raw.row, ctx);
      if (!owned) return { kind: 'skip' };
      if (owned.upgradeCost <= 0 || owned.upgradeCost > ctx.budget) return { kind: 'skip' };
      return { kind: 'upgrade', col: owned.col, row: owned.row, branch: raw.branch ?? null };
    }
    case 'sell': {
      if (raw.col == null || raw.row == null) return { kind: 'skip' };
      const owned = pickOwnedNear(raw.col, raw.row, ctx);
      if (!owned) return { kind: 'skip' };
      return { kind: 'sell', col: owned.col, row: owned.row };
    }
    default:
      return { kind: 'skip' };
  }
}

/** Pick a candidate cell for a placement — preferring the captured
 *  cell exactly, falling back to nearest candidate that has any
 *  path coverage for this tower type. */
function pickPlacementCell(
  capCol: number | null, capRow: number | null, type: { range: number },
  ctx: BotContext,
): Cell | null {
  if (ctx.candidateCells.length === 0) return null;

  // Try exact captured cell first.
  if (capCol !== null && capRow !== null) {
    const exact = ctx.candidateCells.find(c => c.col === capCol && c.row === capRow);
    if (exact) return exact;
    // Captured cell taken / out of zone — pick the closest candidate
    // by Manhattan distance. Ties broken by path coverage.
    return pickNearestCandidate(capCol, capRow, type, ctx);
  }

  // Legacy capture — no cell info. Pick best-coverage candidate.
  return pickBestCoverageCandidate(type, ctx);
}

function pickNearestCandidate(
  col: number, row: number, type: { range: number }, ctx: BotContext,
): Cell | null {
  const paths = ctx.allPaths.filter((p): p is PathPoint[] => !!p && p.length > 0);
  let best: Cell | null = null;
  let bestKey = Infinity;
  for (const c of ctx.candidateCells) {
    const dist = Math.abs(c.col - col) + Math.abs(c.row - row);
    let coverage = 0;
    for (const p of paths) coverage += pathCellsWithinRange(c, p, type.range);
    // Prefer near, then well-covered. Combine: dist*100 - coverage.
    const key = dist * 100 - coverage;
    if (key < bestKey) { bestKey = key; best = c; }
  }
  return best;
}

function pickBestCoverageCandidate(type: { range: number }, ctx: BotContext): Cell | null {
  const paths = ctx.allPaths.filter((p): p is PathPoint[] => !!p && p.length > 0);
  let best: Cell | null = null;
  let bestCoverage = -1;
  for (const c of ctx.candidateCells) {
    let coverage = 0;
    for (const p of paths) coverage += pathCellsWithinRange(c, p, type.range);
    if (coverage > bestCoverage) { bestCoverage = coverage; best = c; }
  }
  return bestCoverage > 0 ? best : null;
}

function pickOwnedNear(col: number, row: number, ctx: BotContext) {
  let best = null;
  let bestDist = Infinity;
  for (const p of ctx.placedTowers) {
    const d = Math.abs(p.col - col) + Math.abs(p.row - row);
    if (d < bestDist) { bestDist = d; best = p; }
  }
  return best;
}

// Registered under id 'human' to match the FeatureExtractor's
// PROPOSER_ORDER slot — proposed actions get by_human=1 set in
// the action features, lighting up the model's human-trained tree
// paths at inference. Same one-hot as captured training rows.
registerBrain('human', () => new HumanReplayBrain());
